### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by fejmek** [qlaffont/paginate-prisma#219]
Hello!

I'm just started using paginate package for my api project, and i found that interference to return type/interface always throws "Type instantiation is excessively deep and possibly infinite." error.
![image](https://github.com/qlaffont/paginate-prisma/assets/50933101/ab32d13c-5924-4745-9bd8-910efb5c45ff)

Code with error:
```typescript
async findAll(pagination: PaginationDto): Promise<PaginationResult & {data: User[]}> {
    return paginate(this.prisma.user)({}, {
      page: pagination.page,
      limit: pagination.limit,
    });
  }
```

User dependency: 
```typescript
import { User } from '@prisma/client';
```

I even try make types more clean and i created this type:
```typescript
export type Pagination<T> = PaginationResult  & { data: T[] }
```

and its also throw "Type instantiation is excessively deep and possibly infinite." error:
```typescript
  async findAll(pagination: PaginationDto): Promise<Pagination<User>> {
    return paginate(this.prisma.user)({}, {
      page: pagination.page,
      limit: pagination.limit,
    });
  }
  ```

I'm pretty sure that maybe im doing some mistake somewhere, but soo how can i declare return type in function without this error?

**Comment by qlaffont** [comment]
I don't reproduce your error, so it comes from your repository. With the code you have provided, I see nothing who can explain your error. Can you provider a reproduction so I can check the error please ?

**Comment by fejmek** [comment]
I never shared reproduction code in issues like that, I copied project without sensitive seed data and with controllers that gives errors and are needed to start app.  
I sent you a invite to repo.  
  
`/src/forums/forums.service.ts`  
`/src/users/users.service.ts`  
  
Thanks for your time

**Comment by qlaffont** [comment]
Yes perfect i just need to reproduce the error to find the fix ! I keep you in touch !

**Comment by qlaffont** [comment]
@fejmek As i see on my typescript checker (VSCode Editor), I have no issue : 
![image](https://github.com/qlaffont/paginate-prisma/assets/10044790/c961c65a-3227-4951-b9f2-97d8831ee495)

So it seems comming from your nest configuration ...

**Comment by qlaffont** [comment]
After investigation, typescript resolution is done so it can infer the type of returned value but due to Prisma typing who is not consistent (regarding of includes), typescript inferring is too deep so it shows this warning to be careful. 

If you want you can ignore this error by doing `//@ts-ignore`.

**Comment by qlaffont** [comment]
PS: don't forget to remove me from your repo !
