### ISSUE TITLE
`groupBy` example

### ISSUE THREAD

**Issue by kasir-barati** [qlaffont/paginate-prisma#262]
Hey,

I am using this lib and it is really easy to work with but I could not find anything mentioning how to `groupBy` results. Any idea?

**Comment by kasir-barati** [comment]
Is groupBy some sort of limitation of this lib?

**Comment by qlaffont** [comment]
Hello, good question ! 

I will check it when i can ^^ if you have time too, i´m open for PR

**Comment by qlaffont** [comment]
After checking the documentation, the groupBy API is very different to findMany API. 
To be honest, If you have time to do a PR, I will check on it, but personally I don't see an urgent need.

**Comment by kasir-barati** [comment]
Many thanks for the reply. I also thought that is the case since with the [current implementation](https://github.com/qlaffont/paginate-prisma/blob/main/src/index.ts#L79) of this lib it is hard to incorporate `groupBy`. But I do not think it is impossible. As for the PR IDK, TBH I am a bit short on time right now, developing my own proj. But will consider it surely @qlaffont.
